version: '{build}'
branches:
  only:
  - master
clone_folder: c:\projects\libnfc
image:
- Visual Studio 2017
configuration:
- Release
- Debug
platform:
- Win32
matrix:
  fast_finish: true

# skip unsupported combinations
init:
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015" )
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013" )
- echo %generator%

before_build:
- cmd: |-
    mkdir build
    cd build
    cmake --version
    cmake .. -DLIBNFC_DRIVER_PN53X_USB=OFF -DLIBNFC_DRIVER_ACR122_USB=OFF -G %generator%
build:
  project: c:\projects\libnfc\build\libnfc.sln
  verbosity: minimal
  parallel: true
